using System;
using System.Collections.Generic;
using System.Text;
using System.ComponentModel.DataAnnotations;

namespace MiddleWay_Controller.IntegrationDatabase
{
    public class _ETL_Inventory
    {
        //[MaxLength( , ErrorMessage = "")]
        public bla _ETL_InventoryUid { get; set; } //INT IDENTITY(1,1) NOT NULL,
        public bla ProcessUid { get; set; } //INT NOT NULL,
        public bla InventoryUid { get; set; } //INT NOT NULL,
        public bla AssetID { get; set; } //VARCHAR(100) NULL,
        public bla Tag { get; set; } //VARCHAR(50) NOT NULL,
        public bla Serial { get; set; } //VARCHAR(50) NULL,
        public bla InventoryTypeUid { get; set; } //INT NOT NULL,
        public bla InventoryTypeName { get; set; } //VARCHAR(100) NOT NULL,
        public bla ItemUid { get; set; } //INT NOT NULL,
        public bla ProductName { get; set; } //VARCHAR(100) NULL,
        public bla ProductDescription { get; set; } //VARCHAR(1000) NULL,
        public bla ProductByNumber { get; set; } //VARCHAR(50) NULL,
        public bla ItemTypeUid { get; set; } //INT NOT NULL,
        public bla ProductTypeName { get; set; } //VARCHAR(50) NOT NULL,
        public bla ProductTypeDescription { get; set; } //VARCHAR(1000) NULL,
        public bla ModelNumber { get; set; } //VARCHAR(100) NULL,
        public bla ManufacturerUid { get; set; } //INT NULL,
        public bla ManufacturerName { get; set; } //VARCHAR(100) NULL,
        public bla AreaUid { get; set; } //INT NULL,
        public bla AreaName { get; set; } //VARCHAR(100) NULL,
        public bla SiteUid { get; set; } //INT NOT NULL,
        public bla SiteID { get; set; } //VARCHAR(100) NULL,
        public bla SiteName { get; set; } //VARCHAR(100) NULL,
        public bla EntityUid { get; set; } //INT NOT NULL,
        public bla EntityName { get; set; } //VARCHAR(50) NOT NULL,
        public bla EntityTypeUid { get; set; } //INT NOT NULL,
        public bla EntityTypeName { get; set; } //VARCHAR(100) NOT NULL,
    public bla StatusID { get; set; } //INT NOT NULL,
        public bla Status { get; set; } //VARCHAR(50) NULL,
        public bla TechDepartmentUid { get; set; } //INT NULL,
        public bla DepartmentName { get; set; } //VARCHAR(50) NULL,
        public bla DepartmentID { get; set; } //VARCHAR(50) NULL,
        public bla FundingSourceUid { get; set; } //INT NOT NULL,
        public bla FundingSource { get; set; } //VARCHAR(500) NULL,
        public bla FundingSourceDescription { get; set; } //VARCHAR(500) NULL,
        public bla PurchasePrice { get; set; } //DECIMAL NULL,
        public bla PurchaseDate { get; set; } //DATETIME NULL,
        public bla ExpirationDate { get; set; } //DATETIME NULL,
        public bla InventoryNotes { get; set; } //VARCHAR(3000) NULL,
        public bla ParentInventoryUid { get; set; } //INT NULL,
        public bla ParentTag { get; set; } //VARCHAR(50) NULL,
        public bla InventorySourceUid { get; set; } //INT NOT NULL,
        public bla InventorySourceName { get; set; } //VARCHAR(100),
        public bla PurchaseUid { get; set; } //INT NOT NULL,
        public bla OrderNumber { get; set; } //VARCHAR(50) NOT NULL,
        public bla PurchaseItemDetailUid { get; set; } //INT NOT NULL,
        public bla LineNumber { get; set; } //INT NOT NULL,
        public bla AccountCode { get; set; } //VARCHAR(100) NULL,
        public bla VendorUid { get; set; } //INT NOT NULL,
        public bla VendorName { get; set; } //VARCHAR(100) NULL,
        public bla VendorAccountNumber { get; set; } //VARCHAR(50) NULL,
        public bla PurchaseItemShipmentUid { get; set; } //INT NOT NULL,
        public bla InvoiceNumber { get; set; } //VARCHAR(25) NULL,
        public bla InvoiceDate { get; set; } //DATE NULL,
        public bla InventoryExt1Uid { get; set; } //INT NULL,
        public bla InventoryMeta1Uid { get; set; } //INT NULL,
        public bla CustomField1Label { get; set; } //VARCHAR(50) NULL,
        public bla CustomField1Value { get; set; } //VARCHAR(50) NULL,
        public bla InventoryExt2Uid { get; set; } //INT NULL,
        public bla InventoryMeta2Uid { get; set; } //INT NULL,
        public bla CustomField2Label { get; set; } //VARCHAR(50) NULL,
        public bla CustomField2Value { get; set; } //VARCHAR(50) NULL,
        public bla InventoryExt3Uid { get; set; } //INT NULL,
        public bla InventoryMeta3Uid { get; set; } //INT NULL,
        public bla CustomField3Label { get; set; } //VARCHAR(50) NULL,
        public bla CustomField3Value { get; set; } //VARCHAR(50) NULL,
        public bla InventoryExt4Uid { get; set; } //INT NULL,
        public bla InventoryMeta4Uid { get; set; } //INT NULL,
        public bla CustomField4Label { get; set; } //VARCHAR(50) NULL,
        public bla CustomField4Value { get; set; } //VARCHAR(50) NULL
    }
}
