CREATE TABLE [dbo].[_ETL_Inventory] (
    [_ETL_InventoryUID]        INT            IDENTITY (1, 1) NOT NULL,
    [ProcessUid]               INT            NOT NULL,
    [InventoryUID]             INT            CONSTRAINT [DF__ETL_Inventory_InventoryUID] DEFAULT ((0)) NOT NULL,
    [AssetID]                  VARCHAR (100)  NULL,
    [Tag]                      VARCHAR (50)   NOT NULL,
    [Serial]                   VARCHAR (50)   NULL,
    [InventoryTypeUID]         INT            CONSTRAINT [DF__ETL_Inventory_InventoryTypeUID] DEFAULT ((0)) NOT NULL,
    [InventoryTypeName]        VARCHAR (100)  NOT NULL,
    [ItemUID]                  INT            CONSTRAINT [DF__ETL_Inventory_ItemUID] DEFAULT ((0)) NOT NULL,
    [ProductName]              VARCHAR (100)  NULL,
    [ProductDescription]       VARCHAR (1000) NULL,
    [ProductByNumber]          VARCHAR (50)   NULL,
    [ItemTypeUID]              INT            CONSTRAINT [DF__ETL_Inventory_ItemTypeUID] DEFAULT ((0)) NOT NULL,
    [ProductTypeName]          VARCHAR (50)   NOT NULL,
    [ProductTypeDescription]   VARCHAR (1000) NULL,
    [ModelNumber]              VARCHAR (100)  NULL,
    [ManufacturerUID]          INT            CONSTRAINT [DF__ETL_Inventory_ManufacturerUID] DEFAULT ((0)) NOT NULL,
    [ManufacturerName]         VARCHAR (100)  NULL,
    [AreaUID]                  INT            CONSTRAINT [DF__ETL_Inventory_AreaUID] DEFAULT ((0)) NOT NULL,
    [AreaName]                 VARCHAR (100)  NULL,
    [SiteUID]                  INT            CONSTRAINT [DF__ETL_Inventory_SiteUID] DEFAULT ((0)) NOT NULL,
    [SiteID]                   VARCHAR (100)  NULL,
    [SiteName]                 VARCHAR (100)  NULL,
    [EntityUID]                INT            CONSTRAINT [DF__ETL_Inventory_EntityUID] DEFAULT ((0)) NOT NULL,
    [EntityID]                 VARCHAR (50)   NOT NULL,
    [EntityName]               VARCHAR (50)   NOT NULL,
    [EntityTypeUID]            INT            CONSTRAINT [DF__ETL_Inventory_EntityTypeUID] DEFAULT ((0)) NOT NULL,
    [EntityTypeName]           VARCHAR (100)  NOT NULL,
    [StatusID]                 INT            NOT NULL,
    [Status]                   VARCHAR (50)   NULL,
    [TechDepartmentUID]        INT            CONSTRAINT [DF__ETL_Inventory_TechDepartmentUID] DEFAULT ((0)) NOT NULL,
    [DepartmentName]           VARCHAR (50)   NULL,
    [DepartmentID]             VARCHAR (50)   NULL,
    [FundingSourceUID]         INT            NOT NULL,
    [FundingSource]            VARCHAR (500)  NULL,
    [FundingSourceDescription] VARCHAR (500)  NULL,
    [PurchasePrice]            DECIMAL (18)   NULL,
    [PurchaseDate]             DATETIME       NULL,
    [ExpirationDate]           DATETIME       NULL,
    [InventoryNotes]           VARCHAR (3000) NULL,
    [ParentInventoryUID]       INT            NULL,
    [ParentTag]                VARCHAR (50)   NULL,
    [InventorySourceUID]       INT            NOT NULL,
    [InventorySourceName]      VARCHAR (100)  NULL,
    [PurchaseUID]              INT            NOT NULL,
    [OrderNumber]              VARCHAR (50)   NOT NULL,
    [PurchaseItemDetailUID]    INT            NOT NULL,
    [LineNumber]               INT            NOT NULL,
    [AccountCode]              VARCHAR (100)  NULL,
    [VendorUID]                INT            NOT NULL,
    [VendorName]               VARCHAR (100)  NULL,
    [VendorAccountNumber]      VARCHAR (50)   NULL,
    [PurchaseItemShipmentUID]  INT            NOT NULL,
    [InvoiceNumber]            VARCHAR (25)   NULL,
    [InvoiceDate]              DATE           NULL,
    [InventoryExt1UID]         INT            NULL,
    [InventoryMeta1UID]        INT            NULL,
    [CustomField1Label]        VARCHAR (50)   NULL,
    [CustomField1Value]        VARCHAR (50)   NULL,
    [InventoryExt2UID]         INT            NULL,
    [InventoryMeta2UID]        INT            NULL,
    [CustomField2Label]        VARCHAR (50)   NULL,
    [CustomField2Value]        VARCHAR (50)   NULL,
    [InventoryExt3UID]         INT            NULL,
    [InventoryMeta3UID]        INT            NULL,
    [CustomField3Label]        VARCHAR (50)   NULL,
    [CustomField3Value]        VARCHAR (50)   NULL,
    [InventoryExt4UID]         INT            NULL,
    [InventoryMeta4UID]        INT            NULL,
    [CustomField4Label]        VARCHAR (50)   NULL,
    [CustomField4Value]        VARCHAR (50)   NULL,
 	[Rejected]                 BIT			  NOT NULL CONSTRAINT [DF__ETL_Inventory_Rejected] DEFAULT 0,
	[RejectedNotes]			   TEXT			  NULL
    CONSTRAINT [PK__ETL_Inventory] PRIMARY KEY CLUSTERED ([_ETL_InventoryUID] ASC),
    CONSTRAINT [FK__ETL_Inventory_Processes] FOREIGN KEY ([ProcessUid]) REFERENCES [dbo].[Processes] ([ProcessUid])
);





