CREATE TABLE [dbo].[_ETL_RawFile](
    [RowID] [int] IDENTITY(1,1) NOT NULL,
    [ProcessUid]  [INT] NOT NULL,
    [RawData] [varchar](max) NULL,
    [RawDataModified] [varchar](max) NULL,
    CONSTRAINT [PK__ETL_RawFile] PRIMARY KEY CLUSTERED ([RowID] ASC) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


