CREATE TABLE [dbo].[InventoryFlatData] (
    [InventoryFlatDataUID]     INT           IDENTITY (1, 1) NOT NULL,
    [ProcessUid]               INT           NOT NULL,
    [RowID]                    INT           NOT NULL,
    [AssetID]                  VARCHAR (MAX) NULL,
    [Tag]                      VARCHAR (MAX) NULL,
    [Serial]                   VARCHAR (MAX) NULL,
    [SiteID]                   VARCHAR (MAX) NULL,
    [SiteName]                 VARCHAR (MAX) NULL,
    [Location]                 VARCHAR (MAX) NULL,
    [LocationType]             VARCHAR (MAX) NULL,
    [Status]                   VARCHAR (MAX) NULL,
    [DepartmentName]           VARCHAR (MAX) NULL,
    [DepartmentID]             VARCHAR (MAX) NULL,
    [FundingSource]            VARCHAR (MAX) NULL,
    [FundingSourceDescription] VARCHAR (MAX) NULL,
    [PurchasePrice]            VARCHAR (MAX) NULL,
    [PurchaseDate]             VARCHAR (MAX) NULL,
    [ExpirationDate]           VARCHAR (MAX) NULL,
    [InventoryNotes]           VARCHAR (MAX) NULL,
    [OrderNumber]              VARCHAR (MAX) NULL,
    [LineNumber]               VARCHAR (MAX) NULL,
    [VendorName]               VARCHAR (MAX) NULL,
    [VendorAccountNumber]      VARCHAR (MAX) NULL,
    [ParentTag]                VARCHAR (MAX) NULL,
    [ProductName]              VARCHAR (MAX) NULL,
    [ProductDescription]       VARCHAR (MAX) NULL,
    [ProductByNumber]          VARCHAR (MAX) NULL,
    [ProductTypeName]          VARCHAR (MAX) NULL,
    [ProductTypeDescription]   VARCHAR (MAX) NULL,
    [ModelNumber]              VARCHAR (MAX) NULL,
    [ManufacturerName]         VARCHAR (MAX) NULL,
    [AreaName]                 VARCHAR (MAX) NULL,
    [CustomField1Value]        VARCHAR (MAX) NULL,
    [CustomField1Label]        VARCHAR (MAX) NULL,
    [CustomField2Value]        VARCHAR (MAX) NULL,
    [CustomField2Label]        VARCHAR (MAX) NULL,
    [CustomField3Value]        VARCHAR (MAX) NULL,
    [CustomField3Label]        VARCHAR (MAX) NULL,
    [CustomField4Value]        VARCHAR (MAX) NULL,
    [CustomField4Label]        VARCHAR (MAX) NULL,
    [InvoiceNumber]            VARCHAR (MAX) NULL,
    [InvoiceDate]              VARCHAR (MAX) NULL,
    [Rejected]                 BIT           CONSTRAINT [DF_InventoryFlatData_Rejected] DEFAULT 0 NOT NULL,
    [RejectedNotes]            TEXT          NULL,
    CONSTRAINT [PK_InventoryFlatData] PRIMARY KEY CLUSTERED ([InventoryFlatDataUID] ASC),
    CONSTRAINT [FK_InventoryFlatData_Processes] FOREIGN KEY ([ProcessUid]) REFERENCES [dbo].[Processes] ([ProcessUid])
);





