CREATE TABLE [dbo].[PurchaseOrderFlatData] (
    [PurchaseOrderFlatDataUID] INT            IDENTITY (1, 1) NOT NULL,
    [ProcessUid]               INT            NOT NULL,
    [RowID]                    INT            NOT NULL,
    [OrderNumber]              VARCHAR (50)   NULL,
    [PurchaseDate]             DATETIME       NULL,
    [LineNumber]               INT            NULL,
    [Status]                   VARCHAR (50)   NULL,
    [VendorName]               VARCHAR (100)  NULL,
    [VendorAccountNumber]      VARCHAR (50)   NULL,
    [SiteID]                   VARCHAR (100)  NULL,
    [SiteName]                 VARCHAR (100)  NULL,
    [ProductName]              VARCHAR (100)  NULL,
    [ProductDescription]       VARCHAR (1000) NULL,
    [ProductTypeName]          VARCHAR (50)   NULL,
    [ProductTypeDescription]   VARCHAR (1000) NULL,
    [SiteAddedSiteID]          VARCHAR (100)  NULL,
    [SiteAddedSiteName]        VARCHAR (100)  NULL,
    [FundingSource]            VARCHAR (500)  NULL,
    [FundingSourceDescription] VARCHAR (500)  NULL,
    [QuantityOrdered]          INT            NULL,
    [QuantityReceived]         INT            NULL,
    [PurchasePrice]            DECIMAL (18)   NULL,
    [AccountCode]              VARCHAR (100)  NULL,
    [DepartmentName]           VARCHAR (50)   NULL,
    [DepartmentID]             VARCHAR (50)   NULL,
    [CFDA]                     VARCHAR (50)   NULL,
    [IsAssociated]             BIT            NULL,
    [Rejected]                 BIT            NOT NULL CONSTRAINT [DF_PurchaseOrderFlatData_Rejected] DEFAULT 0,
    [RejectedNotes]            TEXT           NULL
    CONSTRAINT [PK_PurchaseOrderFlatData] PRIMARY KEY CLUSTERED ([PurchaseOrderFlatDataUID] ASC),
    CONSTRAINT [FK_PurchaseOrderFlatData_Processes] FOREIGN KEY ([ProcessUid]) REFERENCES [dbo].[Processes] ([ProcessUid])
);

