CREATE TABLE [dbo].[PurchaseShipmentFlatData] (
    [PurchaseShipmentFlatDataUID] INT           IDENTITY (1, 1) NOT NULL,
    [ProcessTaskUid]              INT           NOT NULL,
    [RowID]                       INT           NOT NULL,
    [OrderNumber]                 VARCHAR (MAX) NULL,
    [LineNumber]                  VARCHAR (MAX) NULL,
    [ShippedToSiteID]             VARCHAR (MAX) NULL,
    [ShippedToSiteName]           VARCHAR (MAX) NULL,
    [ShippedToSiteAddress]        VARCHAR (MAX) NULL,
    [ShippedToSiteCity]           VARCHAR (MAX) NULL,
    [ShippedToSiteState]          VARCHAR (MAX) NULL,
    [ShippedToSiteZip]            VARCHAR (MAX) NULL,
    [TicketNumber]                VARCHAR (MAX) NULL,
    [QuantityShipped]             VARCHAR (MAX) NULL,
    [TicketedBy]                  VARCHAR (MAX) NULL,
    [TicketedDate]                VARCHAR (MAX) NULL,
    [Status]                      VARCHAR (MAX) NULL,
    [InvoiceNumber]               VARCHAR (MAX) NULL,
    [InvoiceDate]                 VARCHAR (MAX) NULL,
    [Rejected]                    BIT           NOT NULL CONSTRAINT [DF_PurchaseShipmentFlatData_Rejected] DEFAULT ((0)),
    [RejectedNotes]               TEXT          NULL,
    CONSTRAINT [PK_PurchaseShipmentFlatData] PRIMARY KEY CLUSTERED ([PurchaseShipmentFlatDataUID] ASC),
    CONSTRAINT [FK_PurchaseShipmentFlatData_ProcessTasks] FOREIGN KEY ([ProcessTaskUid]) REFERENCES [dbo].[ProcessTasks] ([ProcessTaskUid])
);

