CREATE TABLE [dbo].[PurchaseOrderDetailShipmentFlatData] (
    [PurchaseOrderDetailShipmentFlatDataUID] INT            IDENTITY (1, 1) NOT NULL,
    [ProcessUid]                             INT            NOT NULL,
    [RowID]                                  INT            NOT NULL,
    [OrderNumber]                            VARCHAR (50)   NULL,
    [PurchaseDate]                           DATETIME       NULL,
    [LineNumber]                             INT            NULL,
    [Status]                                 VARCHAR (50)   NULL,
    [VendorName]                             VARCHAR (100)  NULL,
    [VendorAccountNumber]                    VARCHAR (50)   NULL,
    [SiteID]                                 VARCHAR (100)  NULL,
    [SiteName]                               VARCHAR (100)  NULL,
    [ProductName]                            VARCHAR (100)  NULL,
    [ProductDescription]                     VARCHAR (1000) NULL,
    [ProductTypeName]                        VARCHAR (50)   NULL,
    [ProductTypeDescription]                 VARCHAR (1000) NULL,
    [SiteAddedSiteID]                        VARCHAR (100)  NULL,
    [SiteAddedSiteName]                      VARCHAR (100)  NULL,
    [FundingSource]                          VARCHAR (500)  NULL,
    [FundingSourceDescription]               VARCHAR (500)  NULL,
    [QuantityOrdered]                        INT            NULL,
    [QuantityReceived]                       INT            NULL,
    [PurchasePrice]                          DECIMAL (18)   NULL,
    [AccountCode]                            VARCHAR (100)  NULL,
    [DepartmentName]                         VARCHAR (50)   NULL,
    [DepartmentID]                           VARCHAR (50)   NULL,
    [CFDA]                                   VARCHAR (50)   NULL,
    [IsAssociated]                           BIT            NULL,
    [ShippedToSiteID]                        VARCHAR (100)  NULL,
    [ShippedToSiteName]                      VARCHAR (100)  NULL,
    [ShippedToSiteAddress]                   VARCHAR (100)  NULL,
    [ShippedToSiteCity]                      VARCHAR (50)   NULL,
    [ShippedToSiteState]                     VARCHAR (50)   NULL,
    [ShippedToSiteZip]                       VARCHAR (50)   NULL,
    [TicketNumber]                           INT            NULL,
    [QuantityShipped]                        INT            NULL,
    [TicketedBy]                             VARCHAR (50)   NULL,
    [TicketedDate]                           DATETIME       NULL,
    [InvoiceNumber]                          VARCHAR (25)   NULL,
    [InvoiceDate]                            DATETIME       NULL,
    [Rejected]                               BIT            NOT NULL CONSTRAINT [DF_PurchaseOrderDetailShipmentFlatData_Rejected] DEFAULT 0,
    [RejectedNotes]                          TEXT           NULL,
    CONSTRAINT [PK_PurchaseOrderDetailShipmentFlatData] PRIMARY KEY CLUSTERED ([PurchaseOrderDetailShipmentFlatDataUID] ASC),
    CONSTRAINT [FK_PurchaseOrderDetailShipmentFlatData_Processes] FOREIGN KEY ([ProcessUid]) REFERENCES [dbo].[Processes] ([ProcessUid])
);

