CREATE TABLE [dbo].[PurchaseOrderDetailShipmentFlatData] (
    [PurchaseOrderDetailShipmentFlatDataUID] INT            IDENTITY (1, 1) NOT NULL,
    [ProcessUid]                             INT            NOT NULL,
    [RowID]                                  INT            NOT NULL,
    [OrderNumber]                            VARCHAR (MAX)  NULL,
    [PurchaseDate]                           VARCHAR (MAX)  NULL,
    [LineNumber]                             VARCHAR (MAX)  NULL,
    [Status]                                 VARCHAR (MAX)  NULL,
    [VendorName]                             VARCHAR (MAX)  NULL,
    [VendorAccountNumber]                    VARCHAR (MAX)  NULL,
    [SiteID]                                 VARCHAR (MAX)  NULL,
    [SiteName]                               VARCHAR (MAX)  NULL,
    [ProductName]                            VARCHAR (MAX)  NULL,
    [ProductDescription]                     VARCHAR (MAX)  NULL,
    [ProductTypeName]                        VARCHAR (MAX)  NULL,
    [ProductTypeDescription]                 VARCHAR (MAX)  NULL,
    [SiteAddedSiteID]                        VARCHAR (MAX)  NULL,
    [SiteAddedSiteName]                      VARCHAR (MAX)  NULL,
    [FundingSource]                          VARCHAR (MAX)  NULL,
    [FundingSourceDescription]               VARCHAR (MAX)  NULL,
    [QuantityOrdered]                        VARCHAR (MAX)  NULL,
    [QuantityReceived]                       VARCHAR (MAX)  NULL,
    [PurchasePrice]                          VARCHAR (MAX)  NULL,
    [AccountCode]                            VARCHAR (MAX)  NULL,
    [DepartmentName]                         VARCHAR (MAX)  NULL,
    [DepartmentID]                           VARCHAR (MAX)  NULL,
    [CFDA]                                   VARCHAR (MAX)  NULL,
    [IsAssociated]                           VARCHAR (MAX)  NULL,
    [ShippedToSiteID]                        VARCHAR (MAX)  NULL,
    [ShippedToSiteName]                      VARCHAR (MAX)  NULL,
    [ShippedToSiteAddress]                   VARCHAR (MAX)  NULL,
    [ShippedToSiteCity]                      VARCHAR (MAX)  NULL,
    [ShippedToSiteState]                     VARCHAR (MAX)  NULL,
    [ShippedToSiteZip]                       VARCHAR (MAX)  NULL,
    [TicketNumber]                           VARCHAR (MAX)  NULL,
    [QuantityShipped]                        VARCHAR (MAX)  NULL,
    [TicketedBy]                             VARCHAR (MAX)  NULL,
    [TicketedDate]                           VARCHAR (MAX)  NULL,
    [InvoiceNumber]                          VARCHAR (MAX)  NULL,
    [InvoiceDate]                            VARCHAR (MAX)  NULL,
    [Rejected]                               BIT            NOT NULL CONSTRAINT [DF_PurchaseOrderDetailShipmentFlatData_Rejected] DEFAULT 0,
    [RejectedNotes]                          TEXT           NULL,
    CONSTRAINT [PK_PurchaseOrderDetailShipmentFlatData] PRIMARY KEY CLUSTERED ([PurchaseOrderDetailShipmentFlatDataUID] ASC),
    CONSTRAINT [FK_PurchaseOrderDetailShipmentFlatData_Processes] FOREIGN KEY ([ProcessUid]) REFERENCES [dbo].[Processes] ([ProcessUid])
);

