CREATE TABLE [dbo].[PurchaseOrderFlatData] (
    [PurchaseOrderFlatDataUID] INT              IDENTITY (1, 1) NOT NULL,
    [ProcessTaskUid]           INT              NOT NULL,
    [RowID]                    INT              NOT NULL,
    [OrderNumber]              VARCHAR (MAX)    NULL,
    [PurchaseDate]             VARCHAR (MAX)    NULL,
    [LineNumber]               VARCHAR (MAX)    NULL,
    [Status]                   VARCHAR (MAX)    NULL,
    [VendorName]               VARCHAR (MAX)    NULL,
    [VendorAccountNumber]      VARCHAR (MAX)    NULL,
    [SiteID]                   VARCHAR (MAX)    NULL,
    [SiteName]                 VARCHAR (MAX)    NULL,
    [ProductName]              VARCHAR (MAX)    NULL,
    [ProductDescription]       VARCHAR (MAX)    NULL,
    [ProductTypeName]          VARCHAR (MAX)    NULL,
    [ProductTypeDescription]   VARCHAR (MAX)    NULL,
    [SiteAddedSiteID]          VARCHAR (MAX)    NULL,
    [SiteAddedSiteName]        VARCHAR (MAX)    NULL,
    [FundingSource]            VARCHAR (MAX)    NULL,
    [FundingSourceDescription] VARCHAR (MAX)    NULL,
    [QuantityOrdered]          VARCHAR (MAX)    NULL,
    [QuantityReceived]         VARCHAR (MAX)    NULL,
    [PurchasePrice]            VARCHAR (MAX)    NULL,
    [AccountCode]              VARCHAR (MAX)    NULL,
    [DepartmentName]           VARCHAR (MAX)    NULL,
    [DepartmentID]             VARCHAR (MAX)    NULL,
    [CFDA]                     VARCHAR (MAX)    NULL,
    [IsAssociated]             VARCHAR (MAX)    NULL,
    [Rejected]                 BIT              NOT NULL CONSTRAINT [DF_PurchaseOrderFlatData_Rejected] DEFAULT ((0)),
    [RejectedNotes]            TEXT             NULL
    CONSTRAINT [PK_PurchaseOrderFlatData] PRIMARY KEY CLUSTERED ([PurchaseOrderFlatDataUID] ASC),
    CONSTRAINT [FK_PurchaseOrderFlatData_ProcessTasks] FOREIGN KEY ([ProcessTaskUid]) REFERENCES [dbo].[ProcessTasks] ([ProcessTaskUid])
);

